# Generated by Django 3.0.3 on 2020-06-27 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='content_image',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
