# Generated by Django 3.0.7 on 2020-07-08 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_content_content_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='data',
            field=models.TextField(null=True),
        ),
    ]
